eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost
server:
  port: 8085
spring:
  application:
    name: USER-SERVICE
  jpa:
    hibernate: 
      ddl-auto: update
    show-sql: true
    generate-ddl: true
  datasource:
    
    url: jdbc:mysql://localhost:3306/mydb
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver